import random

COMMENTS = [
    "This is so cool!",
    "Absolutely love this!",
    "Looks amazing!",
    "Such a vibe!",
    "Wow, just wow!",
    "This made my day!",
    "You nailed it!",
    "Pure perfection!",
    "Awesome shot!",
    "Stunning!",
    "Speechless.",
    "So beautiful!",
    "Well done!",
    "Iconic.",
    "Obsessed with this!",
    "This gave me chills!",
    "I can’t stop looking at this!",
    "Feeling all the good vibes!",
    "This is everything!",
    "Completely blown away!",
    "Too good to be true!",
    "How do you do it?!",
    "Tell me more about this!",
    "What’s the story behind this?",
    "Love the creativity here!",
    "Can you share more like this?",
    "Would love to see more of this!",
    "You have such a good eye!",
    "This looks so professional!",
    "Your talent is unmatched!",
    "Such great attention to detail!",
    "You always impress me!",
    "This is next level!",
    "Wow.",
    "Love it.",
    "Amazing.",
    "So good.",
    "Perfection.",
    "This feels magical!",
    "The colors are incredible!",
    "How do you make it look so good?",
    "Pure artistry!",
    "Totally mesmerizing!",
    "I could look at this all day!",
    "Such a mood!",
    "The effort really shows here!",
    "This deserves to go viral!",
    "Bravo!",
    "Love everything about this!",
    "Hard to believe how perfect this is!",
    "Effortlessly cool!",
    "Mind blown.",
    "Your work is so inspiring!",
    "This just hits differently.",
    "Where do you get your ideas?",
    "Love the vibe of this!",
    "A masterpiece!",
    "You’ve outdone yourself!",
    "Truly one of a kind!",
    "Love the vibe here! You might enjoy my profile too. ✨",
    "This is so inspiring! Check out my page for more creative ideas. 🌟",
    "Such a great post! Let’s connect and share inspiration. 🔥",
    "I’m loving this! Stop by my profile if you’re curious. 💯",
    "Amazing content! Would love to hear your thoughts on my work. 🙌",
    "Your posts are always a highlight! Come say hi on my page. 🎉",
    "This is absolutely brilliant! Let’s support each other—check out my page. 💡",
    "Such an awesome post! Feel free to drop by my profile anytime. 😊",
    "This is so good! Let’s connect—I’d love to share ideas. 🌈",
    "You always impress! I’d be thrilled to have you visit my profile. 🎨",
    "Beautiful work! Let’s inspire each other—follow if you’d like! 💖",
    "This really stands out! You might enjoy what I’ve been creating too. 👏",
    "Such a mood! Let’s build a creative community together. 🌟",
    "Incredible post! Stop by my page—I think you’ll love it. 🔥",
    "I’m blown away! Let’s connect and support each other’s work. 🤝",
    "This caught my eye! If you enjoy this vibe, check out my page. ✨",
    "So much talent here! Come by my profile—I’d love to hear your thoughts. 😊",
    "I’m obsessed with this! Let’s inspire each other—visit my page. 💯",
    "Such amazing energy here! Feel free to check out my posts too. 🙌",
    "Always love seeing your posts! Come by my profile and say hi. 🎉",
    "This is everything! Let’s connect—I think you’ll enjoy my work too. 💡",
    "Wow, what a post! Stop by my page if you’re looking for more like this. 🌈",
    "You’ve got such great energy! Let’s share ideas—check out my page. 🎨",
    "This is so inspiring! Let’s connect and support each other’s journeys. 🔥",
    "Your posts never disappoint! Feel free to visit my profile anytime. 😊",
    "Such a unique vibe here! I’d love your thoughts on my work. 🙌",
    "This is top-notch! Let’s collaborate—drop by my profile. 💡",
    "I’m loving this energy! Feel free to check out my latest work. 💯",
    "What a great post! Let’s inspire each other—follow if you’d like. 🌟",
    "You’re so creative! I’d be thrilled to connect—visit my page. 🔥",
]

EMOJIS = [
    "🔥",
    "✨",
    "😍",
    "😎",
    "🌟",
    "💯",
    "👏",
    "🌈",
    "🎉",
    "🙌",
    "🖼️",
    "🧡",
    "🎨",
    "🤩",
    "💖",
]


def generate_comment():
    """Generates a random comment."""
    random_emoji = random.choice(EMOJIS) * random.randint(1, 4)
    comment = f"{random.choice(COMMENTS)}{random_emoji}"
    return comment


if __name__ == "__main__":
    print(generate_comment())
